image: mikewilliamson/usesthis-ci

stages:
  - test
  - build

before_script:
  - yarn

test:
  stage: test
  services:
    - name: mikewilliamson/arango-ci
      alias: arangodb
  script:
    - USESTHIS_TEST_DB_URL="http://arangodb:8529" USESTHIS_DB_PASSWORD=test npm test
