image: mikewilliamson/usesthis-ci

cache:
  paths:
    - node_modules

stages:
  - test
  - build

before_script:
  - yarn

test:
  stage: test
  services:
    - name: mikewilliamson/arango-ci
      alias: arangodb
  script:
    - npm test

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: mikewilliamson/usesthis:$CI_COMMIT_SHA
  before_script:
    - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
