version: '2'
services:
  nginx:
    environment:
      - "EMAIL=mike@korora.ca"
      - "DOMAIN=www.usesth.is"
      - "UPSTREAM=backend:3000"
    container_name: lets-nginx
    links:
      - "web:backend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx_conf:/configs:ro"
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-backups:/var/lib/letsencrypt
      - dhparam-cache:/cache
    build: ./nginx
    image: mikewilliamson/nginx
  web:
    environment:
      - USESTHIS_PRODUCTION_DB_URL
      - USESTHIS_PRODUCTION_DB_NAME
      - "PORT=3000"
      - "NODE_ENV=production"
    ports:
      - "${PORT}:3000"
    image: mikewilliamson/usesthis
    links:
      - arangodb
  arangodb:
    environment:
      - "ARANGO_NO_AUTH=1"
    image: arangodb/arangodb:3.0.8
    volumes:
      - data:/var/lib/arangodb3
volumes:
  data:
    driver: local
  letsencrypt:
    driver: local
  letsencrypt-backups:
    driver: local
  dhparam-cache:
    driver: local
